site_name: VK Utility - парсер VK

theme:
  name: material
  custom_dir: docs/overrides
  palette:
      primary: custom
  font:
    text: Roboto
  language: ru
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - toc.integrate 
    - header.autohide
    - announce.dismiss
  
plugins:
  - search 
  - social:
      cards_layout_options:
        background_color: "#0077FF"

nav:
  - Добро пожаловать в VK Utility!: index.md
  - Обзор возможностей: review.md
  - Установка программы: install.md
  - Первый запуск: first-launch.md
  - Что дальше?: whats-next.md
  - Документация:
    - Парсер:
      - Участники группы: guide/filtrator.md
      - Поиск людей: guide/filtrator.md
      - Поиск групп: guide/filtrator.md
      - Парсер админов: guide/filtrator.md
      - Чекер ID пользователей: guide/filtrator.md
      - Друзья пользователей: guide/filtrator.md
      - Генератор ID: guide/filtrator.md
      - Подписки пользователей: guide/filtrator.md
      - Проверка ссылок на бан: guide/filtrator.md
      - Экспорт лайкнувших: guide/filtrator.md
      - Пересечение аудитории: guide/filtrator.md
    - Фильтратор: guide/filtrator.md

markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/vk
      link: https://vk.com/vkutility
      name: 'Сообщество в VK'
    - icon: fontawesome/brands/telegram
      link: https://t.me/iamutility
      name: 'Поддержка в Telegram'

extra_css:
  - stylesheets/extra.css