site_name: PROPARS - парсер VK
site_description: >-
  Многофункциональный парсер VK. Бесплатный навсегда.
  Найдите свою целевую аудиторию в считанные минуты.
site_url: https://vktuility.ru
copyright: ""

theme:
  name: material
  custom_dir: docs/overrides
  favicon: assets/logo.png
  palette:
      primary: custom      
  font:
    text: Roboto
  language: ru
  features:
    - navigation.tabs    
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.expand
    - navigation.sections
    - toc.follow
    - header.autohide
    - announce.dismiss
    - search.share
    - content.code.copy
  
plugins:
  - search
  - social:
      cards_layout_options:
        background_color: "#6389A8"

nav:
  - Главная: index.md
  - Обзор возможностей: review.md
  - Начало работы:
    - Установка и активация: setup-and-launch/install.md
    - Запуск первого задания: setup-and-launch/first-launch.md
  - Руководство пользователя:
    - docs/index.md
    - Парсер:
      - docs/parser/index.md
      - Участники группы: docs/parser/group-members.md
      - Поиск людей: docs/parser/search-people.md
      - Поиск групп: docs/parser/search-groups.md
      - Парсер админов: docs/parser/admins-parser.md
      - Чекер ID пользователей: docs/parser/id-checker.md
      - Друзья пользователей: docs/parser/users-friends.md
      - Генератор ID: docs/parser/id-generator.md
      - Подписки пользователей: docs/parser/users-subscriptions.md
      - Проверка ссылок на бан: docs/parser/check-links-for-ban.md
      - Экспорт лайкнувших: docs/parser/export-likers.md
      - Пересечение аудитории: docs/parser/audience-intersection.md
    - Фильтратор:
      - docs/filtrator/index.md
      - Запуск Фильтратора: docs/filtrator/launch.md
  # - Связь с нами: whats-next.md
    

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: '^'
      #slugify: !!python/object/apply:pymdownx.slugs.slugify
      #  kwds:
      #    case: lower
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic

extra:
  generator: false
  social:
    - icon: fontawesome/brands/vk
      link: https://vk.com/vkutility
      name: 'Сообщество в VK'
    - icon: fontawesome/brands/telegram
      link: https://t.me/propars_ru
      name: 'Канал в Telegram'
    #- icon: fontawesome/brands/telegram
      #link: https://t.me/propars_support
      #name: 'Поддержка в Telegram'
    - icon: fontawesome/brands/discord
      link: https://discord.gg/PBZ4ssYy
      name: 'Discord'


extra_css:
  - stylesheets/extra.css