site_name: VK Utility

theme:
  name: material
  palette:
    scheme: default
    primary: blue
    accent: deep purple
  font:
    text: Roboto
  language: ru
  features:
    - instant
    - tabs
  
plugins:
  - search 

nav:
  - Начало: index.md
  - Установка программы: install.md
  - Первый запуск: first-launch.md
  - 'Документация':
    - guide/filtrator.md

markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/telegram
      # link: https://t.me/vkwave
      name: 'Поддержка в Telegram'
